### ISSUE TITLE
Adapter-Reset alle 5 Minuten

### ISSUE THREAD

**Issue by Michaelnorge** [TA2k/ioBroker.tapo#14]
Ich bekomme genau alle 5 Minuten diese Fehlermeldungen im Log:

```
tapo.0 | 2023-10-07 18:14:43.918 | info | Found 5 devices
-- | -- | -- | --
tapo.0 | 2023-10-07 18:14:43.605 | info | Login succesfull
tapo.0 | 2023-10-07 18:14:42.925 | info | Login tp TAPO App
tapo.0 | 2023-10-07 18:14:42.891 | info | starting. Version 0.0.8 (non-npm: TA2k/ioBroker.tapo#bec54f4bf5d6dbcaf04e8d9e691a75ff1c06e346) in /opt/iobroker/node_modules/iobroker.tapo, node: v18.17.1, js-controller: 5.0.12
host.iobroker-pm | 2023-10-07 18:14:41.899 | info | instance system.adapter.tapo.0 started with pid 2320
host.iobroker-pm | 2023-10-07 18:14:11.787 | info | Restart adapter system.adapter.tapo.0 because enabled
host.iobroker-pm | 2023-10-07 18:14:11.786 | error | instance system.adapter.tapo.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker-pm | 2023-10-07 18:14:11.786 | error | Caught by controller[0]: at processTicksAndRejections (node:internal/process/task_queues:82:21)
host.iobroker-pm | 2023-10-07 18:14:11.786 | error | Caught by controller[0]: at emitErrorCloseNT (node:internal/streams/destroy:116:3)
host.iobroker-pm | 2023-10-07 18:14:11.786 | error | Caught by controller[0]: at emitErrorNT (node:internal/streams/destroy:151:8)
host.iobroker-pm | 2023-10-07 18:14:11.786 | error | Caught by controller[0]: at Socket.emit (node:domain:489:12)
host.iobroker-pm | 2023-10-07 18:14:11.786 | error | Caught by controller[0]: at Socket.emit (node:events:514:28)
host.iobroker-pm | 2023-10-07 18:14:11.786 | error | Caught by controller[0]: at Socket.socketErrorListener (node:_http_client:501:9)
host.iobroker-pm | 2023-10-07 18:14:11.786 | error | Caught by controller[0]: at ClientRequest.emit (node:domain:489:12)
host.iobroker-pm | 2023-10-07 18:14:11.786 | error | Caught by controller[0]: at ClientRequest.emit (node:events:526:35)
host.iobroker-pm | 2023-10-07 18:14:11.786 | error | Caught by controller[0]: at ClientRequest.<anonymous> (/opt/iobroker/node_modules/onvif/lib/cam.js:328:4)
host.iobroker-pm | 2023-10-07 18:14:11.786 | error | Caught by controller[0]: at Cam.<anonymous> (/opt/iobroker/node_modules/onvif/lib/events.js:309:14)
host.iobroker-pm | 2023-10-07 18:14:11.785 | error | Caught by controller[0]: TypeError: callback.call is not a function
tapo.0 | 2023-10-07 18:14:11.698 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
tapo.0 | 2023-10-07 18:14:11.698 | info | terminating
tapo.0 | 2023-10-07 18:14:11.686 | error | callback.call is not a function
tapo.0 | 2023-10-07 18:14:11.685 | error | TypeError: callback.call is not a function at Cam.<anonymous> (/opt/iobroker/node_modules/onvif/lib/events.js:309:14) at ClientRequest.<anonymous> (/opt/iobroker/node_modules/onvif/lib/cam.js:328:4) at ClientRequest.emit (node:events:526:35) at ClientRequest.emit (node:domain:489:12) at Socket.socketErrorListener (node:_http_client:501:9) at Socket.emit (node:events:514:28) at Socket.emit (node:domain:489:12) at emitErrorNT (node:internal/streams/destroy:151:8) at emitErrorCloseNT (node:internal/streams/destroy:116:3) at processTicksAndRejections (node:internal/process/task_queues:82:21)
tapo.0 | 2023-10-07 18:14:11.685 | error | uncaught exception: callback.call is not a function
```

ioBroker läuft auf Proxmox, habe das System heute aufgesetzt aus einem Backup einer Raspberry Installation, somit ist das System auf dem neusten Stand.

Alle anderen Adapter laufen soweit, nur mit TAPO habe ich das Problem.

Die Fehlermeldungen (die alle exakt 5 Minuten erscheinen) sagen mir leider nichts. 
Den Updateintervall innerhalb der App habe ich auf 60 Sekunden laufen.

Objekte habe ich gelöscht, auch den Adapter habe ich gelöscht und neu aufgesetzt - alles ohne Erfolg.
Außerdem habe ich testweise alle anderen testweise Adapter deaktiviert, sowie piHole ausgeschaltet.

Ich hatte identische Accounts bei den Apps Tapo und Kasa. Bei einem Update von Tapo sind plötzlich zwei Steckdosen mit in der Liste im Handy erschienen, die allerdings nicht im ioBroker-Log zu sehen waren.

Also habe ich einen komplett neuen Account bei Tapo eingerichtet nur mit den fünf Kameras, aber der Fehler ist immer noch da.

Ich komme einfach nicht dahinter, was der Fehler sein könnte.

**Comment by Michaelnorge** [comment]
Chat-GPT bringt diese Antwort: 

_**Der Fehlermeldungstext zeigt, dass es ein Problem mit der Ausführung eines JavaScript-Codes gibt, der in einem ioBroker-Adapter namens "tapo.0" auftritt. Hier sind die relevanten Teile der Fehlermeldung:

1. "TypeError: callback.call is not a function" - Dies deutet darauf hin, dass irgendwo im Code versucht wird, eine Funktion namens "callback.call" aufzurufen, aber diese Funktion nicht als solche definiert oder verfügbar ist. Dies ist ein häufiger Fehler, der auftritt, wenn eine Funktion nicht ordnungsgemäß definiert oder importiert wurde.

2. "at Cam.<anonymous> (/opt/iobroker/node_modules/onvif/lib/events.js:309:14)" - Dies zeigt den Ort im Code an, an dem der Fehler auftritt. Es scheint, dass der Fehler im Modul "onvif" auftritt und in der Datei "events.js" auf Zeile 309.

3. "instance system.adapter.tapo.0 terminated with code 1 (JS_CONTROLLER_STOPPED)" - Dies bedeutet, dass der Adapter "tapo.0" aufgrund dieses Fehlers beendet wurde.

Um diesen Fehler zu beheben, sollten Sie die folgenden Schritte durchführen:

1. Überprüfen Sie den Code im "tapo.0" Adapter, insbesondere an der Stelle, an der die "callback.call"-Funktion aufgerufen wird. Stellen Sie sicher, dass diese Funktion korrekt definiert und verfügbar ist.

2. Überprüfen Sie die Version des "onvif"-Moduls und stellen Sie sicher, dass es auf dem neuesten Stand ist. Möglicherweise gibt es ein Update, das diesen Fehler behebt.

3. Wenn der Fehler weiterhin besteht, sollten Sie die Community oder Entwickler des "tapo.0"-Adapters kontaktieren, um weitere Unterstützung bei der Fehlerbehebung zu erhalten.

Es ist wichtig zu beachten, dass diese Fehlermeldung spezifisch für Ihre ioBroker-Installation und die verwendeten Module ist, daher können die genauen Details und Lösungen je nach Umgebung variieren.**_

Ich gehe also nicht davon aus das der Fehler an meiner Installation liegt, oder liege ich da falsch?

**Comment by TA2k** [comment]
die GitHub version hat mehr debug logs bitte den debug log schicken
tombox2020@gmail.com

**Comment by Michaelnorge** [comment]
Das Update des Adapters hat super geklappt, die Fehlermeldungen sind weg!
Vielen Dank!
