### ISSUE TITLE
After few days: "322 Error: Request failed with status code 403" - ok again after restart

### ISSUE THREAD

**Issue by akudev** [TA2k/ioBroker.tapo#25]
**Describe the bug**  
After a few (2-4?) days of working fine, the adapter no longer turns the light bulbs on/off. Object changes don't do anything.
The error message
```
322 Error: Request failed with status code 403
```
starts appearing in the log after each refreshInterval.

After restarting the adapter everything works perfectly fine again. So I assume something happens on startup which also should happen when this error starts appearing. ***Maybe there is an access token which needs to be refreshed from time to time?***

**To Reproduce**  
1. Keep active for days

**Expected behavior**  
It should continue working infinitely. But it no longer switches light bulbs and shows "322 Error: Request failed with status code 403"

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: latest from GitHub (0.2.0)
 - JS-Controller version: 5.0.16
 - Node version: 18.17.1
 - Operating system: Raspbian GNU/Linux 11 (bullseye)

![image](https://github.com/TA2k/ioBroker.tapo/assets/4866568/c67438e3-5d12-42f6-af02-22564ab50957)

**Comment by TA2k** [comment]
please try the GitHub version

**Comment by akudev** [comment]
Thanks! Ok, I just installed the new code, so I'll have to wait a few days until I see whether it works.

What I accidentally noticed: when I restart the adapter while the light bulb is offline (no power), then I get a `TypeError: cannot read property "message" of undefined.` whenever there is a communication attempt. Even after the light bulb has come online. Only an adapter restart fixes it. I don't think this can come from the new code. I probably just haven't had this situation previously.

**Comment by akudev** [comment]
Ok, after a week of running fine (the bulb was accidentally removed from power after 2-3 days, so I had to restart the test period) I can confirm this issue is fixed. Thanks!!

**Comment by xCruziX** [comment]
This happens to me from time to time and this message spams my logs everytime the adapter tries to connect.
![image](https://github.com/user-attachments/assets/54db4767-ef07-4a1a-a9ee-07c000e35f4e)

I am using v0.3.3
