### ISSUE TITLE
P110, error 52, Since the firmware update yesterday.

### ISSUE THREAD

**Issue by Heisenberg2018** [TA2k/ioBroker.tapo#27]
**Describe the bug**  
Since the firmware update yesterday, my Tapo p110 only gets error 52 in iobroker and cannot connect. 

**To Reproduce**  
Happened with the firmware update:
Tapo P110(EU)_V1_1.3.0 Build 230905

**Expected behavior**  
I already thought that there were problems because the firmware also indicated changes to the login security in the changelog

**Screenshots & Logfiles**  
2023-12-01 11:37:21.572 error 52 - Get Device Info failed

**Versions:** 
Adapter:
0.2.0

**Additional context**  
It looks like TP-Link is currently patching all WLAN devices, and it looks like you have to rework the adapter for every device that has the new update!?

**Comment by OberstVonGatow** [comment]
What do you mean with "must be renewed in the adapter"? I restarted and reinstalled the adapter with new Login and MFA but still get there Error.

And you were right one of my p110 still had an old Firmware.

I also have a old HS110 connected with the tapo App but don't think that should be an issue.

**Comment by Heisenberg2018** [comment]
Is there any news about an adapter update?

**Comment by Hant0r** [comment]
If you also have this problem, please like the first post. That way, not everyone has to comment here that they are also affected and the developer can quickly see how urgent it is

**Comment by TA2k** [comment]
I waiting for homebridge implementation that they fixing this

**Comment by Uwe4313** [comment]
Tapo P115 Nano Plug is also affected.

**Comment by ad2012** [comment]
Seems to be fixed but waiting for pull... https://github.com/apatsufas/homebridge-tapo-p100/pull/47

**Comment by Heisenberg2018** [comment]
Is there no more update coming?

**Comment by padman74** [comment]
I'm also waiting. Or is there any other option to get the power consumption into IOBroker?

**Comment by Heisenberg2018** [comment]
I would also be interested in a solution because suddenly and unexpectedly the responsible developer is apparently no longer active after 10 years. I have the feeling that nothing is happening anymore and that's why I need a replacement solution.

**Comment by TA2k** [comment]
As mentioned still waiting for the homebridge fix

**Comment by MaPaSoTo** [comment]
hmm, not sure. Still have this problem. Is it fixed or do we still wait?

**Comment by Heisenberg2018** [comment]
The sockets are working again Update to the latest GitHub version.
