### ISSUE TITLE
Logs fill with error message 'Request failed with status code 403' and the adapter is not working

### ISSUE THREAD

**Issue by ymickler** [TA2k/ioBroker.tapo#46]
**Describe the bug**  
My log get spammed by the mentioned error message:

```
tapo.0 | 2024-10-07 14:37:45.096 | error | Request failed with status code 403
-- | -- | -- | --
tapo.0 | 2024-10-07 14:37:45.093 | error | Request failed with status code 403
tapo.0 | 2024-10-07 14:36:45.093 | error | Request failed with status code 403
tapo.0 | 2024-10-07 14:36:45.090 | error | Request failed with status code 403
tapo.0 | 2024-10-07 14:35:45.092 | error | Request failed with status code 403
```

The refresh interval is set to 60s.
This happens every time the adapter is running for +1 day and leads to a not working adapter.

**To Reproduce**  
- the adapter is running for +1 day.

**Expected behavior**  
The Adapter is working without the error message and I can control my devices.

**Screenshots & Logfiles**  
```
tapo.0 | 2024-10-07 14:37:45.096 | error | Request failed with status code 403
-- | -- | -- | --
tapo.0 | 2024-10-07 14:37:45.093 | error | Request failed with status code 403
tapo.0 | 2024-10-07 14:36:45.093 | error | Request failed with status code 403
tapo.0 | 2024-10-07 14:36:45.090 | error | Request failed with status code 403
tapo.0 | 2024-10-07 14:35:45.092 | error | Request failed with status code 403
```

**Versions:**  
 - Adapter version: v0.3.3
 - JS-Controller version: 6.0.11
 - Node version: 20.16.0
 - Operating system: buanet docker

**Additional context**  
Perhaps related: https://github.com/TA2k/ioBroker.tapo/issues/25

**Comment by tecfreakz** [comment]
This might ba analog to https://github.com/TA2k/ioBroker.tapo/issues/38 (need unterstanding german or translating from german to unterstand). TP-Link crashes his API with one of the last updates, there are also much discussions in Home Assistant bords and some other placec, whe the API is used. TP Link announced for november this year will an update to be released with a fix or new api. This should solve it we hope :)

**Comment by TA2k** [comment]
Please test 0.3.4
