### ISSUE TITLE
Bitte Anpassung der Fehlermeldungen im Log

### ISSUE THREAD

**Issue by Michaelnorge** [TA2k/ioBroker.tapo#8]
Ich nutze unter Anderem auch eine Innenkamera, die an einer Schaltsteckdose angeschlossen ist und daher nur läuft, wenn niemand zu Hause ist. 
Leider spinnt der Adapter rum und schreibt mir alle 10 Sekunden Fehlermeldungen ins Log.

Kann man vielleicht diese Fehlermeldungen nicht als "error" sondern als "warning" ins Log schreiben?
Damit wäre mir schon sehr geholfen.

Alternativ wäre ein Abhaken der vom Adapter gefundenen Geräte super. Dann könnte ich eben diese Kamera aushaken!

Danke :-)

**Comment by TA2k** [comment]
welcher Fehler genau

**Comment by Michaelnorge** [comment]
![image](https://github.com/TA2k/ioBroker.tapo/assets/42386692/77293776-6e5e-4a31-b3bf-576fa36fd9a9)

Diesen hier.
Hat aber Abhilfe geschafft die Updateintervalle im Adapter (von 10 Sekunden auf 1 Stunde) zu erhöhen.
Hatte gemerkt daß dies keine direkten Auswirkungen hat, weil der Adapter wohl lokal die Geräte steuert.

**Comment by TA2k** [comment]
Teste bitte mal die GitHub version

**Comment by Michaelnorge** [comment]
> Teste bitte mal die GitHub version

![image](https://github.com/TA2k/ioBroker.tapo/assets/42386692/bc5e3b72-bdcc-46d0-b0d9-03c1abda5355)

Keine Änderung leider.

**Comment by TA2k** [comment]
Ich brauch ein kurzen debug log um das besser zu identifizieren

**Comment by Michaelnorge** [comment]
> Ich brauch ein kurzen debug log um das besser zu identifizieren

Kann ich Dir das über Email schicken?
nach 20 Sekunden ist der Log bereits voll mit MAC-Adressen und weiteren Zahlen die ich nicht deuten kann, möchte das lieber nicht hier öffentlich reinkopieren.

**Comment by TA2k** [comment]
tombox2020@gmail.com

**Comment by Michaelnorge** [comment]
Ok, Log geschickt :-)

**Comment by Michaelnorge** [comment]
Guten Morgen!
Ich hab den Adapter einmal komplett runtergeschmissen und von Github neu installiert, da ich gesehen habe, daß dort gestern programmiert wurde :-)))

Trotzdem gehen die FetchError immer noch als "error" ins log, nicht als "warning".
![image](https://github.com/TA2k/ioBroker.tapo/assets/42386692/2a6df4bc-8c5e-459a-b040-3ba90f357a44)

**Comment by Michaelnorge** [comment]
Jetzt kommt die Fehlermeldung als Warnung:
![image](https://github.com/TA2k/ioBroker.tapo/assets/42386692/cb02eea3-ff26-4cdb-8303-a860207ac5d4)

Das kann ich jetzt in den Adaptereinstellungen wegfiltern :-)

Perfekt, danke für die tolle schnelle Hilfe!
Schönes Wochenende!
